const x = 19.51;
console.log(x.toFixed(3));
console.log(x.toFixed(2));
console.log(x.toFixed(1));
console.log(x.toFixed(0));
const y = 3800.5;
console.log(y.toExponential(4));
console.log(y.toExponential(3));
console.log(y.toExponential(2));
console.log(y.toExponential(1));
console.log(y.toExponential(0));
const z = 1000;
console.log(z.toPrecision(5));
console.log(z.toPrecision(4));
console.log(z.toPrecision(3));
console.log(z.toPrecision(2));
console.log(z.toPrecision(1));
const a = 12;
console.log(a.toString());
console.log(a.toString(10));
console.log(a.toString(16));
console.log(a.toString(12));
console.log(a.toString(8));
console.log(a.toString(2));

console.log(Math.pow(3, 3));
console.log(Math.sqrt(4));
console.log(Math.cbrt(27));
console.log(Math.min(2, 35, 1, 0.1));
